	<table><TR><TD valign=top><img style='height: 30px' src='/images/WKC-Logo2.png'></TD>
	<TD valign=top><B>Delivery Process System (Self Help)</B>
	</TD></TR>
	<TR><TD colspan=2>
		<table>
		<HR>
		<TR><TD valign=top width='60px'>
			<img src='/images/Features.jpg'>
		</TD>
		<TD valign=top>
			<ul class='help'>
			<li>To create a new user of the system, simply enters the details in the "<B>Add New User Account</B>" form.</li>
			<li>Click on the Search tab to search for the users currently exist in the system.</li>
			</ul>
		</TD></TR>
		</table>
	
	</TD></TR>
	<TR><TD colspan=2><HR>
	<table>
	<TR><TD valign=top width='60px'>
		<img src='/images/QuickTips.jpg'>
	</TD>
	<TD valign=top>
		<ul class='help'>
				<li>Accounts that is no longer being used should set to <B>Not Active</B> and not encouraged to be deleted. This will maintain the integrity of the system.</li>
			</ul>
	</TD></TR></table>
	
	</TD></TR>
	<!--
	<TR><TD colspan=2><HR>
	<table>
	<TR><TD valign=top width='60px'>
		<img src='/images/Questions.jpg'>
	</TD>
	<TD valign=top>
		<B>Got question in regards to this page?</B><BR>
		Drop us a line here:<BR>
		<form action='/admin/system/message' method=POST>
		<textarea cols=45 rows=4 name='message'></textarea><BR>
		<input type=submit name='SubmitMessage' value='Submit'>
		</form>
	</TD></TR></table>
	
	
	</TD></TR>
	-->
	
	
	</table>
	
	<BR><BR><BR>