
<script language='Javascript'>

function validateEmail(email) { 
    var re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    return re.test(email);
} 

function isValidPassword(input)
{
	 if (input.length < 8)
		return false;


	 var reg = /[a-zA-Z]/;
	 var reg2 = /[0-9]/;
	 return reg.test(input) && reg2.test(input);
}  



$(document).ready(function() {
	$("#SubmitEmail").click (function() { 
		
		var error = false;
		
        if ($('#Email').val()=='') { 
			
			$('#Email').poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_('Please enter your email address registered in CLAS')?>', className: 'tip-yellow', showOn:'none', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5, timeOnScreen: 3000});
			$('#Email').poshytip('show');

			error = true;
		}else if (!validateEmail($('#Email').val())) { 
			
			$('#Email').poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_('The email you entered is not valid')?>', className: 'tip-yellow', showOn:'none', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5, timeOnScreen: 3000});
			$('#Email').poshytip('show');

			error = true;
		}	
		
        if ($('#Captcha').val()=='') { 
			
			$('#Captcha').poshytip({ bgImageFrameSize:8, content: '<img src="/images/icons/IconAlert.png"><?=$this->translate->_('Please enter the code shown below')?>', className: 'tip-yellow', showOn:'none', alignTo: 'target', alignX: 'right',alignY: 'center',offsetX: 5, timeOnScreen: 3000});
			$('#Captcha').poshytip('show');

			error = true;
		}			
		
		if (error)
			return false; 			
	})
	

});
</script>

<div class="loginpg_wrapper">


<div class="login_content_wrapper">          
	<div class="loginbox">
    	<div class="input_login_wrapper">
            <form id='formlogin' action='/auth/index/forgotpasswordrequest' method='POST'>
			<div class="toplogin_txtbox_user">
              <input <?=$disable?> style='border: 0; outline:0; color: black;' type="text" id="Email"  name='Email' placeholder="Email" autocomplete="off" class="input_login" />
            </div>
            <div class="toplogin_txtbox_pass">
              <input <?=$disable?> style='border: 0; outline:0; color: black;'  type="text" id="Captcha" name="Captcha" placeholder="Please enter code below" class="input_login" />
            </div>
			<div style='margin-top:22px; margin-left:-5px; float: left;' >
				<img style="height: 40px; border: solid 2px silver; border-radius: 5px;" id='captcha-img' src='/captcha/<?php echo $this->captchaId?>.png' alt='captcha'>
			</div>
			
            <div style="margin-top:32px; margin-left:150px;">
			<input type=submit name="SubmitEmail" id="SubmitEmail" value="Submit">
			<input type='hidden' id='captcha-id' value='<?php echo $this->captchaId?>' name='CaptchaID' />
			</div>
			</form>
        </div>

		
		<div style='margin-left: auto;margin-right: auto; width: 290px; margin-top: 28px;'>
			<a target='_blank' href='http://www.the-afc.com'><img src='/images/Logo-Icon-small.png'></a>
			<a target='_blank' href='http://www.the-afc.com/competition/afc-champions-league'><img src='/images/comp_ACL.png'></a>
			<a target='_blank' href='http://www.the-afc.com/competition/afc-cup'><img src='/images/comp_AFCCUP.png'></a>
			
		</div>
		
    </div>
</div>
<h3>AFC Club Administrative System (CLAS) - Password Reset</h3>
To reset your password, please enter your username and the new password and click Reset Password button to change your password.
</div>
<script language='Javascript'>
var FinishedOnce = false;

$("#bgvid").bind("loadeddata", function() {
	$("#idLoadVid").css("visibility", "hidden");
})

$("#bgvid").bind("ended", function() {
	if (!FinishedOnce) {
		setTimeout(function(){
			$('#divVideo #bgvid source').attr('src', 'video/intro_loop.mp4');
			$('#divVideo #bgvid').attr('loop', 'loop');
			$("#divVideo #bgvid")[0].load();	
			$("#divVideo #bgvid")[0].play();	
			
		}, 3000);
		
		FinishedOnce = true;
		$("#idLoadVid").css("visibility", "visible");

	}else
	{
		$("#divVideo #bgvid")[0].load();	
		$("#divVideo #bgvid")[0].play();	
	}
 
});

</script>

<!--
<div class="alert alert-info">Please enter your username and password to login into AFC Club Licensing System</div>
	<div id="login-container-main">
		<form id='formlogin' action='/auth/index/authlogin' method='POST'>
		<img src='/images/Logo-Small.png'>
		<BR><BR>
		 <div class="control-group">
			<div class="controls">
			  <input <?=$disable?> type="text" id="userID"  name='userID' placeholder="Username" autocomplete="off">
			</div>
		  </div>
		  <div class="control-group">
			<div class="controls">
			  <input <?=$disable?>  type="password" id="userPassword" name="userPassword" placeholder="Password">
			</div>
		  </div>
		  <button <?=$disable?> type="submit" style='margin-top: 10px;'>Login</button>
		</form>
	  </div>

</form> 

-->
