

	<!-- ---------------------------------------------------------- -->
	<!-- ------------------- SALES FROM ------------------------ -->
	<!-- ---------------------------------------------------------- -->
<? if ($this->userInfo->ACLRole == "AdminSystem" || $this->userInfo->ACLRole == "Admin") { ?>	
<form enctype="multipart/form-data"  action='/default/index/index/#tabs1' method=POST  data-ajax="false">
 
<div class="md-card">
	<div class="md-card-toolbar" style='background-color: #87cfe7'>
		 <h3 class="md-card-toolbar-heading-text">
			New Sales Details
		</h3>
	</div>
	<div class="md-card-content" style='background-color: #dcf1f8'>
	
	<div class="uk-form-row">
		<div class="uk-grid">
			<div class="uk-width-medium-1-5" style='-webkit-transition: width 1s; transition: width 1s;'>
				<div class="md-input-wrapper md-input-wrapper-success"><label>Currency</label>
					<input type="text" id="SalesCurrency" name="SalesCurrency" class="md-input SalesCurrency" value=""><span class="md-input-bar"></span>
					<input type="hidden" id="SalesCurrencyID" name="SalesCurrencyID" value="">
				</div>
				
			</div>
			<div class="uk-width-medium-1-5 clsCurrencyRate">
				<div class="md-input-wrapper md-input-wrapper-success"><label>Rate</label>
					<input type="text" id="SalesPriceExchangeRate" name="SalesPriceExchangeRate" class="md-input" value="">
					<span class="md-input-bar"></span></div>
			</div>
			<div class="uk-width-medium-2-5">
				<div class="md-input-wrapper md-input-wrapper-success"><label>Selling Price</label>
					<input type="text" id="SalesPrice" name="SalesPrice" class="md-input" value="">
					<span class="md-input-bar"></span></div>
			</div>
			<div class="uk-width-medium-1-5">
				<div class="md-input-wrapper md-input-wrapper-success"><label>Terms</label>
					<input type="text" id="SalesTerms" name="SalesTerms" class="md-input SalesTerms" value=""><span class="md-input-bar"></span>
					<input type="hidden" id="SalesTermsID" name="SalesTermsID" value="">
				</div>
			</div>
		   
		</div>
	</div>
	
	<div class="uk-form-row">
			<div class="uk-grid">
				<div class="uk-width-medium-1-3">
					<div class="md-input-wrapper md-input-wrapper-success"><label><i class="uk-input-group-icon uk-icon-calendar"></i> Cust. PO Received </label>
						<input type="text" name="CustomerPOReceivedDate" class="md-input CustomerPOReceivedDate" value=""><span class="md-input-bar"></span>
					</div>
				</div>
				<div class="uk-width-medium-1-3">
				<div class="md-input-wrapper md-input-wrapper-success"><label><i class="uk-input-group-icon uk-icon-calendar"></i> Cust Expected Date</label>
					<input type="text" id="SalesExpDate" name="SalesExpDate" class="md-input SalesExpDate" value=""><span class="md-input-bar"></span></div>
					
				</div>
				<div class="uk-width-medium-1-3">
					<div class="md-input-wrapper md-input-wrapper-success"><label><i class="uk-input-group-icon uk-icon-calendar"></i> Goods Ready Date</label>
						<input type="text" id="SalesReadyDate" name="SalesReadyDate" class="md-input SalesReadyDate" value=""><span class="md-input-bar"></span></div>
				</div>
				<!-- <div class="uk-width-medium-1-3">
					<div class="md-input-wrapper md-input-wrapper-success"><label><i class="uk-input-group-icon uk-icon-calendar"></i> Invoice Date</label>
						<input type="text" id="SalesInvoiceDate" name="SalesInvoiceDate" class="md-input" value="<?=$this->SalesInvoiceDate?>"><span class="md-input-bar"></span></div>
					
				</div>
				-->
				
			   
			</div>
		</div>
		<div class="uk-form-row">
			<div class="uk-grid">
				<div class="uk-width-medium-1-1">
					<div class="md-input-wrapper md-input-wrapper-success">
						
							<input type=submit name='CreateSales' id='CreateSales' value='Create'>
							<input type="hidden" id="JobID" name="JobID" value="<?=$this->edit_job?>">
					</div>
				</div>
				
			</div>
		</div>
	
	

									
	
	</div>
</div>
</form>
<? } ?>